// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRGQAnmXH1KfnNR_Qqwc6N108AAjOzs14',
    appId: '1:824244528633:web:c053cab2a5431b42ce8928',
    messagingSenderId: '824244528633',
    projectId: 'stockmarketpredictor-7e6d9',
    authDomain: 'stockmarketpredictor-7e6d9.firebaseapp.com',
    storageBucket: 'stockmarketpredictor-7e6d9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsw8uIBVbi1oT2B-gVVc_blXWcxfVfpPk',
    appId: '1:824244528633:android:4094c8b2e8bdaa85ce8928',
    messagingSenderId: '824244528633',
    projectId: 'stockmarketpredictor-7e6d9',
    storageBucket: 'stockmarketpredictor-7e6d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJrUUkEUINGxk-p76iB7rvhyRW56Uo32U',
    appId: '1:824244528633:ios:3a820d00fdcdab76ce8928',
    messagingSenderId: '824244528633',
    projectId: 'stockmarketpredictor-7e6d9',
    storageBucket: 'stockmarketpredictor-7e6d9.firebasestorage.app',
    iosBundleId: 'com.example.stockMarketPredictor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJrUUkEUINGxk-p76iB7rvhyRW56Uo32U',
    appId: '1:824244528633:ios:3a820d00fdcdab76ce8928',
    messagingSenderId: '824244528633',
    projectId: 'stockmarketpredictor-7e6d9',
    storageBucket: 'stockmarketpredictor-7e6d9.firebasestorage.app',
    iosBundleId: 'com.example.stockMarketPredictor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRGQAnmXH1KfnNR_Qqwc6N108AAjOzs14',
    appId: '1:824244528633:web:db8207dd14404898ce8928',
    messagingSenderId: '824244528633',
    projectId: 'stockmarketpredictor-7e6d9',
    authDomain: 'stockmarketpredictor-7e6d9.firebaseapp.com',
    storageBucket: 'stockmarketpredictor-7e6d9.firebasestorage.app',
  );
}
